namespace: w2fly

replicaCount: 1

labels:
  group: w2fly
  cluster: pre

service:
  containerPort: 4000

#Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: tst-w2fly.internal.w2m.com
      paths:
        - serviceName: tst-ssr-w2fly
          servicePort: 80
          path: /

resources:
  limits:
    cpu: 600m
    memory: 300Mi
  requests:
    cpu: 10m
    memory: 50Mi
