ingress:
  http:
    - ingressPath: /web
      serviceName: front-promotions-web-develop
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

front:
  image:
    repository: REPOSITORYIMAGETOREPLACE
    tag: TAGNAMETOREPLACE
  minReplicas: 1
  hpa:
    enabled: true
    cpu: 70
    memory: 70
    maxReplicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 200m
      memory: 200Mi
  deployment:
    environment: develop
    context: front-promotions-web
    values:
    - type: env
      keys:
      - name: deployment_ID
        value: DEPLOYMENTIDTOREPLACE
      - name: NODE_ENV
        value: develop

varnish:
  varnishBackendService: front-promotions-web-develop
  minReplicas: 1
  hpa:
    enabled: true
    cpu: 70
    memory: 70
    maxReplicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 200m
      memory: 200Mi
